/*
 * Copyright © 2026 ObjectBox Ltd. <https://objectbox.io>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.config;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import io.objectbox.flatbuffers.BaseVector;
import io.objectbox.flatbuffers.Constants;
import io.objectbox.flatbuffers.FlatBufferBuilder;
import io.objectbox.flatbuffers.Table;

/**
 * Options to enable and configure WAL.
 */
@SuppressWarnings("unused")
public final class WalOptions extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static WalOptions getRootAsWalOptions(ByteBuffer _bb) { return getRootAsWalOptions(_bb, new WalOptions()); }
  public static WalOptions getRootAsWalOptions(ByteBuffer _bb, WalOptions obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public WalOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Flags to enable and change default WAL behavior, e.g. no sync to disk option.
   */
  public long walFlags() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  /**
   * The WAL file gets consolidated when it reached this size limit when opening the database.
   * This setting is meant for applications that prefer to consolidate on startup,
   * which may avoid consolidations on commits while the application is running.
   * The default is 4096 (4 MB).
   */
  public long maxWalFileSizeOnOpenInKbyte() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  /**
   * The WAL file gets consolidated when it reaches this size limit after a commit.
   * As consolidation takes some time, it is a trade-off between accumulating enough data
   * and the time the consolidation takes (longer with more data).
   * The default is 16384 (16 MB).
   */
  public long maxWalFileSizeInKbyte() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createWalOptions(FlatBufferBuilder builder,
      long walFlags,
      long maxWalFileSizeOnOpenInKbyte,
      long maxWalFileSizeInKbyte) {
    builder.startTable(3);
    WalOptions.addMaxWalFileSizeInKbyte(builder, maxWalFileSizeInKbyte);
    WalOptions.addMaxWalFileSizeOnOpenInKbyte(builder, maxWalFileSizeOnOpenInKbyte);
    WalOptions.addWalFlags(builder, walFlags);
    return WalOptions.endWalOptions(builder);
  }

  public static void startWalOptions(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addWalFlags(FlatBufferBuilder builder, long walFlags) { builder.addInt(0, (int) walFlags, (int) 0L); }
  public static void addMaxWalFileSizeOnOpenInKbyte(FlatBufferBuilder builder, long maxWalFileSizeOnOpenInKbyte) { builder.addLong(1, maxWalFileSizeOnOpenInKbyte, 0L); }
  public static void addMaxWalFileSizeInKbyte(FlatBufferBuilder builder, long maxWalFileSizeInKbyte) { builder.addLong(2, maxWalFileSizeInKbyte, 0L); }
  public static int endWalOptions(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public WalOptions get(int j) { return get(new WalOptions(), j); }
    public WalOptions get(WalOptions obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

