// automatically generated by the FlatBuffers compiler, do not modify

package objectstore;

/**
 * Not really an enum, but binary flags to use across languages
 */
public final class PropertyFlags {
  private PropertyFlags() { }
  public static final byte ID = 1;
  public static final byte INDEXED = 2;
  /**
   * Unused yet
   */
  public static final byte INDEX_PARTIAL_SKIP_NULL = 4;
  /**
   * Unused yet
   */
  public static final byte NOT_NULL = 8;

  public static final String[] names = { "ID", "INDEXED", "", "INDEX_PARTIAL_SKIP_NULL", "", "", "", "NOT_NULL", };

  public static String name(int e) { return names[e - ID]; }
}

