// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.model;

/**
 * Not really an enum, but binary flags to use across languages
 */
public final class EntityFlags {
  private EntityFlags() { }
  /**
   * Use the default (no arguments) constructor to create entities
   */
  public static final int USE_NO_ARG_CONSTRUCTOR = 1;

  public static final String[] names = { "USE_NO_ARG_CONSTRUCTOR", };

  public static String name(int e) { return names[e - USE_NO_ARG_CONSTRUCTOR]; }
}

