// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.model;

/**
 * Not really an enum, but binary flags to use across languages
 */
public final class OrderFlags {
  private OrderFlags() { }
  public static final int DESCENDING = 1;
  /**
   * For strings only
   */
  public static final int IGNORE_CASE_ASCII = 2;
  /**
   * For scalars only
   */
  public static final int UNSIGNED = 4;
  /**
   * null values will be put first (Default)
   */
  public static final int NULLS_FIRST = 8;
  /**
   * null values will be put last
   */
  public static final int NULLS_LAST = 16;
  /**
   * null values are equal to zero (scalars) or empty strings ("")
   */
  public static final int NULLS_ZERO = 32;
}

