// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.model;

/**
 * Not really an enum, but binary flags to use across languages
 */
public final class OrderFlags {
  private OrderFlags() { }
  public static final int DESCENDING = 1;
  /**
   * For strings only
   */
  public static final int IGNORE_CASE_ASCII = 2;
  /**
   * For scalars only
   */
  public static final int UNSIGNED = 4;
  /**
   * Unused yet
   */
  public static final int NULLS_LAST = 8;
  /**
   * Unused yet (Default)
   */
  public static final int NULLS_FIRST = 16;
  /**
   * Unused yet
   */
  public static final int NULLS_ZERO = 32;
}

