// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.model;

/**
 * Not really an enum, but binary flags to use across languages
 */
public final class PropertyFlags {
  private PropertyFlags() { }
  /**
   * One long property on an entity must be the ID
   */
  public static final byte ID = 1;
  public static final byte INDEXED = 2;
  /**
   * Unused yet
   */
  public static final byte INDEX_PARTIAL_SKIP_NULL = 4;
  /**
   * Unused yet: Unique index
   */
  public static final byte UNIQUE = 8;
  /**
   * Unused yet
   */
  public static final byte NOT_NULL = 16;

  public static final String[] names = { "ID", "INDEXED", "", "INDEX_PARTIAL_SKIP_NULL", "", "", "", "UNIQUE", "", "", "", "", "", "", "", "NOT_NULL", };

  public static String name(int e) { return names[e - ID]; }
}

