// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.model;

/**
 * Not really an enum, but binary flags to use across languages
 */
public final class PropertyFlags {
  private PropertyFlags() { }
  /**
   * One long property on an entity must be the ID
   */
  public static final byte ID = 1;
  /**
   * On languages like Java, a non-primitive type is used (aka wrapper types, allowing null)
   */
  public static final byte NON_PRIMITIVE_TYPE = 2;
  /**
   * Unused yet
   */
  public static final byte NOT_NULL = 4;
  public static final byte INDEXED = 8;
  /**
   * Unused yet
   */
  public static final byte INDEX_PARTIAL_SKIP_NULL = 16;
  /**
   * Unused yet: Unique index
   */
  public static final byte UNIQUE = 32;
}

