/*
 * Copyright 2021 ObjectBox Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.model;

/**
 * Flags to adjust sync behavior like additional logging.
 */
@SuppressWarnings("unused")
public final class SyncFlags {
  private SyncFlags() { }
  /**
   * Enable (rather extensive) logging on how IDs are mapped (local <-> global)
   */
  public static final int DEBUG_LOG_ID_MAPPING = 1;

  public static final String[] names = { "DEBUG_LOG_ID_MAPPING", };

  public static String name(int e) { return names[e - DEBUG_LOG_ID_MAPPING]; }
}

