[versions]
agp = "8.13.2" # https://developer.android.com/build/releases/gradle-plugin
androidxLifecycle = "2.6.1" # https://developer.android.com/jetpack/androidx/releases/lifecycle
# Not using Paging v3 as it pulls in Kotlin
androidxPaging = "2.1.2" # https://developer.android.com/jetpack/androidx/releases/paging
androidxTest = "1.5.0" # https://developer.android.com/jetpack/androidx/releases/test
androidxTestJunit = "1.1.5" # https://developer.android.com/jetpack/androidx/releases/test
junit = "4.13.2"
publish-plugin = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
robolectric = "4.10.3" # https://github.com/robolectric/robolectric/releases
spotbugs-plugin = "6.0.26" # https://github.com/spotbugs/spotbugs-gradle-plugin/releases
versions = "0.54.0" # https://github.com/ben-manes/gradle-versions-plugin/releases

[libraries]
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "androidxLifecycle" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidxPaging" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
