[versions]
# The versions of Gradle, Kotlin, Kotlin Coroutines and Android Gradle Plugin must be compatible.
# Check
# - https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin
# - https://github.com/Kotlin/kotlinx.coroutines#readme
# Note: when updating to a new minor version also have to increase the minimum
# compiler and standard library version supported by consuming projects, see
# objectbox-kotlin/ build script.
# Note: if AGP Upgrade Assitant doesn't open, temporarily change to the com.android.application
# plugin below. Also be aware that the latest version is likely not supported by IntelliJ IDEA.
agp = "9.0.1" # https://developer.android.com/build/releases/gradle-plugin
kotlin = "2.4.0"
kotlin-coroutines = "1.11.0"
# For objectbox-kotlin: a version of coroutines that depends on the same or older version of the
# Kotlin standard library (org.jetbrains.kotlin:kotlin-stdlib) set as coreLibrariesVersion in its
# build script. To find a suitable version, maybe use
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
kotlin-coroutines-compat = "1.10.2" # 1.11.0 requires stdlib 2.2.20, so use 1.10.2
# Dokka includes its own version of the Kotlin compiler, so it does not have to match the used
# Kotlin version. But it might not understand new language features.
kotlin-dokka = "2.2.0" # https://github.com/Kotlin/dokka/releases

androidx-lifecycle = "2.6.1" # https://developer.android.com/jetpack/androidx/releases/lifecycle
# Not using Paging v3 as it pulls in Kotlin
androidx-paging = "2.1.2" # https://developer.android.com/jetpack/androidx/releases/paging
androidx-test = "1.7.0" # https://developer.android.com/jetpack/androidx/releases/test
androidx-test-junit = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/test
essentials = "3.1.0"
jsr305 = "3.0.2"
junit = "4.13.2"
# Mockito 5 requires Java 11: this is fine as CI doesn't run RxJava tests with older JDKs
mockito = "5.23.0" # https://github.com/mockito/mockito/releases/
play-services-nearby = "19.3.0" # https://developers.google.com/android/guides/releases
publish-plugin = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
robolectric = "4.16.1" # https://github.com/robolectric/robolectric/releases
rxjava2 = "2.2.21"
rxjava3 = "3.0.11"
spotbugs-annotations = "4.10.2" # https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md
spotbugs-plugin = "6.5.8" # https://github.com/spotbugs/spotbugs-gradle-plugin/releases
turbine = "1.2.1" # https://github.com/cashapp/turbine/releases
versions = "0.54.0" # https://github.com/ben-manes/gradle-versions-plugin/releases

[libraries]
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "androidx-lifecycle" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
essentials = { module = "org.greenrobot:essentials", version.ref = "essentials" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit = { module = "junit:junit", version.ref = "junit" }
#noinspection SimilarGradleDependency
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
#noinspection SimilarGradleDependency
kotlin-coroutines-core-compat = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines-compat" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
play-services-nearby = { module = "com.google.android.gms:play-services-nearby", version.ref = "play-services-nearby" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava3" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# build-logic dependencies
buildLogic-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin-dokka" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
