[versions]
# The versions of Gradle, Kotlin, Kotlin Coroutines and Android Gradle Plugin must be compatible.
# Check
# - https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin
# - https://github.com/Kotlin/kotlinx.coroutines#readme
# Note: when updating to a new minor version also have to increase the minimum
# compiler and standard library version supported by consuming projects, see
# objectbox-kotlin/ build script.
agp = "8.13.2" # https://developer.android.com/build/releases/gradle-plugin
kotlin = "2.4.0"
kotlin-coroutines = "1.11.0"
# For objectbox-kotlin: a version of coroutines that depends on the same or older version of the
# Kotlin standard library (org.jetbrains.kotlin:kotlin-stdlib) set as coreLibrariesVersion in its
# build script. To find a suitable version, maybe use
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
kotlin-coroutines-compat = "1.10.2" # 1.11.0 requires stdlib 2.2.20, so use 1.10.2
# Dokka includes its own version of the Kotlin compiler, so it must not match
# the used Kotlin version. But it might not understand new language features.
kotlin-dokka = "1.9.20"

androidxLifecycle = "2.6.1" # https://developer.android.com/jetpack/androidx/releases/lifecycle
# Not using Paging v3 as it pulls in Kotlin
androidxPaging = "2.1.2" # https://developer.android.com/jetpack/androidx/releases/paging
androidxTest = "1.5.0" # https://developer.android.com/jetpack/androidx/releases/test
androidxTestJunit = "1.1.5" # https://developer.android.com/jetpack/androidx/releases/test
essentials = "3.1.0"
jsr305 = "3.0.2"
junit = "4.13.2"
mockito = "3.8.0"
publish-plugin = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
robolectric = "4.10.3" # https://github.com/robolectric/robolectric/releases
rxjava2 = "2.2.21"
rxjava3 = "3.0.11"
spotbugs-annotations = "4.8.6" # https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md
spotbugs-plugin = "6.5.8" # https://github.com/spotbugs/spotbugs-gradle-plugin/releases
turbine = "0.5.2"
versions = "0.54.0" # https://github.com/ben-manes/gradle-versions-plugin/releases

[libraries]
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "androidxLifecycle" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidxPaging" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
essentials = { module = "org.greenrobot:essentials", version.ref = "essentials" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit = { module = "junit:junit", version.ref = "junit" }
#noinspection SimilarGradleDependency
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
#noinspection SimilarGradleDependency
kotlin-coroutines-core-compat = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines-compat" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava3" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
