package io.objectbox.test.proguard;

import io.objectbox.BoxStore;
import io.objectbox.BoxStoreBuilder;
import io.objectbox.ModelBuilder;
import io.objectbox.ModelBuilder.EntityBuilder;
import io.objectbox.model.PropertyFlags;
import io.objectbox.model.PropertyType;


// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.
/**
 * Starting point for working with your ObjectBox. All boxes are set up for your objects here.
 * <p>
 * First steps (Android): get a builder using {@link #builder()}, call {@link BoxStoreBuilder#androidContext(Object)},
 * and {@link BoxStoreBuilder#build()} to get a {@link BoxStore} to work with.
 */
public class MyObjectBox {

    public static BoxStoreBuilder builder() {
        BoxStoreBuilder builder = new BoxStoreBuilder(getModel());
        builder.entity("ObfuscatedEntity", ObfuscatedEntity.class, ObfuscatedEntityCursor.class, new ObfuscatedEntity_());
        return builder;
    }

    private static byte[] getModel() {
        ModelBuilder modelBuilder = new ModelBuilder();
        modelBuilder.lastEntityId(1, 1001L);
        modelBuilder.lastIndexId(0, 0L);

        EntityBuilder entityBuilder;

        entityBuilder = modelBuilder.entity("ObfuscatedEntity");
        entityBuilder.id(1, 1001L).lastPropertyId(3, 1004L);
        entityBuilder.property("id", PropertyType.Long).id(1, 1002L)
            .flags(PropertyFlags.ID);
        entityBuilder.property("myInt", PropertyType.Int).id(2, 1003L);
        entityBuilder.property("myString", PropertyType.String).id(3, 1004L);
        entityBuilder.entityDone();

        return modelBuilder.build();
    }

}
