package io.objectbox.test.proguard;

import io.objectbox.annotation.*;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity "ObfuscatedEntity".
 */
@Entity
public class ObfuscatedEntity {

    @Id
    private long id;
    private int myInt;
    private String myString;

    @Generated
    public ObfuscatedEntity() {
    }

    public ObfuscatedEntity(long id) {
        this.id = id;
    }

    @Generated
    public ObfuscatedEntity(long id, int myInt, String myString) {
        this.id = id;
        this.myInt = myInt;
        this.myString = myString;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public int getMyInt() {
        return myInt;
    }

    public void setMyInt(int myInt) {
        this.myInt = myInt;
    }

    public String getMyString() {
        return myString;
    }

    public void setMyString(String myString) {
        this.myString = myString;
    }

}
