package io.objectbox.test.proguard;


import io.objectbox.Cursor;
import io.objectbox.Properties;
import io.objectbox.Transaction;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Cursor for DB entity "ObfuscatedEntity".
 */
public class ObfuscatedEntityCursor extends Cursor<ObfuscatedEntity> {

    private static Properties PROPERTIES = new ObfuscatedEntity_();


    private final int _myIntId;
    private final int _myStringId;

    public ObfuscatedEntityCursor(Transaction tx, long cursor) {
        super(tx, cursor, PROPERTIES);
        _myIntId = getPropertyId("myInt");
        _myStringId = getPropertyId("myString");
    }

    @Override
    public final long getId(ObfuscatedEntity entity) {
        return entity.getId();
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @Override
    public final long put(ObfuscatedEntity entity) {
        String myString = entity.getMyString();
        int _id2 = myString != null ? _myStringId : 0;

        long __assignedId = collect313311(cursor, entity.getId(), PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                _id2, myString, 0, null,
                0, null, 0, null,
                _myIntId, entity.getMyInt(), 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.setId(__assignedId);
        return __assignedId;
    }

    // TODO do we need this? @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
