
package io.objectbox.test.proguard;

import io.objectbox.Properties;
import io.objectbox.Property;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Properties for entity "ObfuscatedEntity". Can be used for QueryBuilder and for referencing DB names.
 */
public class ObfuscatedEntity_ implements Properties {

    public static final String __NAME_IN_DB = "ObfuscatedEntity";

    public final static Property id = new Property(0, 1, long.class, "id", true, "id");
    public final static Property myInt = new Property(1, 2, int.class, "myInt");
    public final static Property myString = new Property(2, 3, String.class, "myString");

    public final static Property[] __ALL_PROPERTIES = {
        id,
        myInt,
        myString
    };

    public final static Property __ID_PROPERTY = id;

    @Override
    public Property[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public Property getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public String getDbName() {
        return __NAME_IN_DB;
    }

}
