package io.objectbox.tree;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.internal.CursorFactory;
import io.objectbox.relation.ToOne;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * ObjectBox generated Cursor implementation for "MetaBranch".
 * Note that this is a low-level class: usually you should stick to the Box class.
 */
public final class MetaBranchCursor extends Cursor<MetaBranch> {
    @Internal
    static final class Factory implements CursorFactory<MetaBranch> {
        @Override
        public Cursor<MetaBranch> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
            return new MetaBranchCursor(tx, cursorHandle, boxStoreForEntities);
        }
    }

    private static final MetaBranch_.MetaBranchIdGetter ID_GETTER = MetaBranch_.__ID_GETTER;


    private final static int __ID_name = MetaBranch_.name.id;
    private final static int __ID_description = MetaBranch_.description.id;
    private final static int __ID_parentId = MetaBranch_.parentId.id;

    public MetaBranchCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
        super(tx, cursor, MetaBranch_.__INSTANCE, boxStore);
    }

    @Override
    public long getId(MetaBranch entity) {
        return ID_GETTER.getId(entity);
    }

    /**
     * Puts an object into its box.
     *
     * @return The ID of the object within its box.
     */
    @Override
    public long put(MetaBranch entity) {
        ToOne<MetaBranch> parent = entity.parent;
        if(parent != null && parent.internalRequiresPutTarget()) {
            Cursor<MetaBranch> targetCursor = getRelationTargetCursor(MetaBranch.class);
            try {
                parent.internalPutTarget(targetCursor);
            } finally {
                targetCursor.close();
            }
        }
        String name = entity.name;
        int __id1 = name != null ? __ID_name : 0;
        String description = entity.description;
        int __id2 = description != null ? __ID_description : 0;

        long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                __id1, name, __id2, description,
                0, null, 0, null,
                __ID_parentId, entity.parent.getTargetId(), 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0);

        entity.id = __assignedId;

        attachEntity(entity);
        return __assignedId;
    }

    private void attachEntity(MetaBranch entity) {
        // Transformer will create __boxStore field in entity and init it here:
        // entity.__boxStore = boxStoreForEntities;
    }

}
