// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox;

/**
 * Not really an enum, but binary flags to use across languages
 */
public final class DebugFlags {
  private DebugFlags() { }
  public static final int LOG_TRANSACTIONS = 1;
  public static final int LOG_QUERIES = 2;

  public static final String[] names = { "LOG_TRANSACTIONS", "LOG_QUERIES", };

  public static String name(int e) { return names[e - LOG_TRANSACTIONS]; }
}

