// automatically generated by the FlatBuffers compiler, do not modify

package objectstore.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ModelProperty extends Table {
  public static ModelProperty getRootAsModelProperty(ByteBuffer _bb) { return getRootAsModelProperty(_bb, new ModelProperty()); }
  public static ModelProperty getRootAsModelProperty(ByteBuffer _bb, ModelProperty obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ModelProperty __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public int type() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  /**
   * bit flags: e.g. indexed, not-nullable
   */
  public int flags() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createModelProperty(FlatBufferBuilder builder,
      int nameOffset,
      int type,
      int flags) {
    builder.startObject(3);
    ModelProperty.addName(builder, nameOffset);
    ModelProperty.addFlags(builder, flags);
    ModelProperty.addType(builder, type);
    return ModelProperty.endModelProperty(builder);
  }

  public static void startModelProperty(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addByte(1, (byte)type, 0); }
  public static void addFlags(FlatBufferBuilder builder, int flags) { builder.addByte(2, (byte)flags, 0); }
  public static int endModelProperty(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

