// automatically generated by the FlatBuffers compiler, do not modify

package objectstore.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ModelEntity extends Table {
  public static ModelEntity getRootAsModelEntity(ByteBuffer _bb) { return getRootAsModelEntity(_bb, new ModelEntity()); }
  public static ModelEntity getRootAsModelEntity(ByteBuffer _bb, ModelEntity obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ModelEntity __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ModelProperty properties(int j) { return properties(new ModelProperty(), j); }
  public ModelProperty properties(ModelProperty obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int propertiesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createModelEntity(FlatBufferBuilder builder,
      int nameOffset,
      int propertiesOffset) {
    builder.startObject(2);
    ModelEntity.addProperties(builder, propertiesOffset);
    ModelEntity.addName(builder, nameOffset);
    return ModelEntity.endModelEntity(builder);
  }

  public static void startModelEntity(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addProperties(FlatBufferBuilder builder, int propertiesOffset) { builder.addOffset(1, propertiesOffset, 0); }
  public static int createPropertiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endModelEntity(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

