
package io.objectbox.index.model;

import javax.annotation.Nullable;

import io.objectbox.BoxStore;
import io.objectbox.Cursor;
import io.objectbox.EntityInfo;
import io.objectbox.Property;
import io.objectbox.Transaction;
import io.objectbox.internal.CursorFactory;
import io.objectbox.internal.IdGetter;

// THIS CODE was originally GENERATED BY ObjectBox.

/**
 * Properties for entity "EntityLongIndex". Can be used for QueryBuilder and for referencing DB names.
 */
public class EntityLongIndex_ implements EntityInfo<EntityLongIndex> {

    public static final String __NAME_IN_DB = "EntityLongIndex";

    public final static Property id = new Property(0, 7, long.class, "id", true, "_id");
    public final static Property indexedLong = new Property(1, 1, long.class, "indexedLong");
    public final static Property float1 = new Property(2, 2, Float.class, "float1");
    public final static Property float2 = new Property(3, 3, Float.class, "float2");
    public final static Property float3 = new Property(4, 4, Float.class, "float3");
    public final static Property float4 = new Property(5, 5, Float.class, "float4");
    public final static Property float5 = new Property(6, 6, Float.class, "float5");

    public final static Property[] __ALL_PROPERTIES = {
            id,
            indexedLong,
            float1,
            float2,
            float3,
            float4,
            float5
    };

    public final static Property __ID_PROPERTY = id;

    @Override
    public Property[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public Property getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public String getEntityName() {
        return "EntityLongIndex";
    }

    @Override
    public String getDbName() {
        return __NAME_IN_DB;
    }

    @Override
    public Class<EntityLongIndex> getEntityClass() {
        return EntityLongIndex.class;
    }

    @Override
    public IdGetter<EntityLongIndex> getIdGetter() {
        return new IdGetter<EntityLongIndex>() {
            @Override
            public long getId(EntityLongIndex object) {
                return object.id;
            }
        };
    }

    @Override
    public CursorFactory<EntityLongIndex> getCursorFactory() {
        return new CursorFactory<EntityLongIndex>() {
            @Override
            public Cursor<EntityLongIndex> createCursor(Transaction tx, long cursorHandle, @Nullable BoxStore boxStoreForEntities) {
                return new EntityLongIndexCursor(tx, cursorHandle, boxStoreForEntities);
            }
        };
    }
}
