
package io.objectbox.index.model;

import io.objectbox.Properties;
import io.objectbox.Property;

// THIS CODE was originally GENERATED BY ObjectBox.

/**
 * Properties for entity "EntityLongIndex". Can be used for QueryBuilder and for referencing DB names.
 */
public class EntityLongIndex_ implements Properties {

    public static final String __NAME_IN_DB = "EntityLongIndex";

    public final static Property id = new Property(0, 7, long.class, "id", true, "_id");
    public final static Property indexedLong = new Property(1, 1, long.class, "indexedLong");
    public final static Property float1 = new Property(2, 2, Float.class, "float1");
    public final static Property float2 = new Property(3, 3, Float.class, "float2");
    public final static Property float3 = new Property(4, 4, Float.class, "float3");
    public final static Property float4 = new Property(5, 5, Float.class, "float4");
    public final static Property float5 = new Property(6, 6, Float.class, "float5");

    public final static Property[] __ALL_PROPERTIES = {
        id,
            indexedLong,
            float1,
            float2,
            float3,
            float4,
            float5
    };

    public final static Property __ID_PROPERTY = id;

    @Override
    public Property[] getAllProperties() {
        return __ALL_PROPERTIES;
    }

    @Override
    public Property getIdProperty() {
        return __ID_PROPERTY;
    }

    @Override
    public String getDbName() {
        return __NAME_IN_DB;
    }

}
