/*
 * Copyright 2024 ObjectBox Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package io.objectbox.sync.server;

/**
 * Special bit flags used in cluster mode only.
 */
@SuppressWarnings("unused")
public final class ClusterFlags {
  private ClusterFlags() { }
  /**
   * Indicates that this cluster always stays in the "follower" cluster role.
   * Thus, it does not participate in leader elections.
   * This is useful e.g. for weaker cluster nodes that should not become leaders.
   */
  public static final int FixedFollower = 1;
}

