// This convention plugin creates a task named "javadocJar" that creates a JAR
// from HTML API docs generated with Dokka suitable to publish to Maven Central.

import org.gradle.jvm.tasks.Jar

plugins {
    id("org.jetbrains.dokka")
}

// Web API docs for objectbox-java packages, URL must end with a /
private val javaApiDocsBaseUrl = "https://objectbox.io/docfiles/java/current/"
// Note: In JDK 9+ the package-list file was renamed to element-list
private val javaApiDocsPackageListUrl = "${javaApiDocsBaseUrl}element-list"

// https://kotlinlang.org/docs/dokka-gradle-configuration-options.html
dokka {
    dokkaPublications.html {
        outputDirectory.set(layout.buildDirectory.dir("docs/javadoc"))
    }
    dokkaSourceSets.configureEach {
        // Create external links to ObjectBox Java API docs
        externalDocumentationLinks.register("objectbox-java-docs") {
            url(javaApiDocsBaseUrl)
            packageListUrl(javaApiDocsPackageListUrl)
        }
    }
}

val javadocJar by tasks.registering(Jar::class) {
    description = "Javadoc JAR containing HTML API docs generated by Dokka"
    group = "build"
    // Classifier as required by Maven Central
    // https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources
    archiveClassifier.set("javadoc")
    from(tasks.dokkaGeneratePublicationHtml.flatMap { it.outputDirectory })
}
